// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
 module.exports = {
  TCC803xSidebar: [
    {
      type: 'category',
      label: 'HW',
      items: [
        {
          type: 'category',
          label: 'Application Note',
          items: [
            { type: 'autogenerated', dirName: 'TCC803x/HW/Application Note' }
          ]
        },
        {
          type: 'category',
          label: 'User Guide',
          items: [
            { type: 'autogenerated', dirName: 'TCC803x/HW/User Guide' }
          ]
        }
      ],
    },
    {
      type: 'category',
      label: 'SW',
      items: [
        {
          type: 'category',
          label: 'Android',
          items: [
            {
              type: 'category',
              label: 'Android 13',
              items: [
                { type: 'autogenerated', dirName: 'TCC803x/SW/Android/Android 13' }
              ]
            },
            {
              type: 'category',
              label: 'Android 14',
              items: [
                { type: 'autogenerated', dirName: 'TCC803x/SW/Android/Android 14' }
              ]
            },
            {
              type: 'category',
              label: 'Android 15',
              items: [
                { type: 'autogenerated', dirName: 'TCC803x/SW/Android/Android 15' }
              ]
            }
          ]
        }
      ],
    },
  ],

  TCC805xSidebar: [
    {
      type: 'category',
      label: 'HW',
      items: [
        {
          type: 'category',
          label: 'Application Note',
          items: [
            { type: 'autogenerated', dirName: 'TCC805x/HW/Application Note' }
          ]
        },
        {
          type: 'category',
          label: 'User Guide',
          items: [
            { type: 'autogenerated', dirName: 'TCC805x/HW/User Guide' }
          ]
        }
      ],
    },
    {
      type: 'category',
      label: 'SW',
      items: [
        {
          type: 'category',
          label: 'Android',
          items: [
            {
              type: 'category',
              label: 'Android 13',
              items: [
                { type: 'autogenerated', dirName: 'TCC805x/SW/Android/Android 13' }
              ]
            },
            {
              type: 'category',
              label: 'Android 14',
              items: [
                { type: 'autogenerated', dirName: 'TCC805x/SW/Android/Android 14' }
              ]
            },
            {
              type: 'category',
              label: 'Android 15',
              items: [
                { type: 'autogenerated', dirName: 'TCC805x/SW/Android/Android 15' }
              ]
            }
          ]
        }
      ],
    },
  ],

  TCC807xSidebar: [
    {
      type: 'category',
      label: 'HW',
      items: [
        {
          type: 'category',
          label: 'Application Note',
          items: [
            { type: 'autogenerated', dirName: 'TCC807x/HW/Application Note' }
          ]
        },
        {
          type: 'category',
          label: 'User Guide',
          items: [
            { type: 'autogenerated', dirName: 'TCC807x/HW/User Guide' }
          ]
        }
      ],
    },
    {
      type: 'category',
      label: 'SW',
      items: [
        {
          type: 'category',
          label: 'Android',
          items: [
            {
              type: 'category',
              label: 'Android 13',
              items: [
                { type: 'autogenerated', dirName: 'TCC807x/SW/Android/Android 13' }
              ]
            },
            {
              type: 'category',
              label: 'Android 14',
              items: [
                { type: 'autogenerated', dirName: 'TCC807x/SW/Android/Android 14' }
              ]
            },
            {
              type: 'category',
              label: 'Android 15',
              items: [
                { type: 'autogenerated', dirName: 'TCC807x/SW/Android/Android 15' }
              ]
            }
          ]
        }
      ],
    },
  ],

  TCC200xSidebar: [
    {
      type: 'category',
      label: 'HW',
      items: [
        {
          type: 'category',
          label: 'Application Note',
          items: [
            { type: 'autogenerated', dirName: 'TCC200x/HW/Application Note' }
          ]
        },
        {
          type: 'category',
          label: 'User Guide',
          items: [
            { type: 'autogenerated', dirName: 'TCC200x/HW/User Guide' }
          ]
        }
      ],
    },
    {
      type: 'category',
      label: 'SW',
      items: [
        {
          type: 'category',
          label: 'Android',
          items: [
            {
              type: 'category',
              label: 'Android 13',
              items: [
                { type: 'autogenerated', dirName: 'TCC200x/SW/Android/Android 13' }
              ]
            },
            {
              type: 'category',
              label: 'Android 14',
              items: [
                { type: 'autogenerated', dirName: 'TCC200x/SW/Android/Android 14' }
              ]
            },
            {
              type: 'category',
              label: 'Android 15',
              items: [
                { type: 'autogenerated', dirName: 'TCC200x/SW/Android/Android 15' }
              ]
            }
          ]
        }
      ],
    },
  ],
};