// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
module.exports = {
  TCC803xSidebar: [
    {
      type: 'category',
      label: 'HW',
      items: [
        {
          type: 'category',
          label: 'Application Note',
          items: [
            { type: 'autogenerated', dirName: 'TCC803x/HW/Application Note' }
          ],
        },
        {
          type: 'category',
          label: 'User Guide',
          items: [
            { type: 'autogenerated', dirName: 'TCC803x/HW/User Guide' }
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'SW',
      items: [
        {
          type: 'category',
          label: 'Android',
          items: [
            {
              type: 'category',
              label: 'Android 12',
              items: [
                {
                  type: 'category',
                  lable: 'Getting Started',
                  item: [
                    {type: 'autogenerated', dirName: 'TCC803x/SW/Android/Android 12/Getting Started'}
                  ] 
                }
              ],
            },
            {
              type: 'category',
              label: 'Android 13',
              items: [
                { type: 'autogenerated', dirName: 'TCC803x/SW/Android/Android 13' }
              ],
            },
            {
              type: 'category',
              label: 'Android 14',
              items: [
                { type: 'autogenerated', dirName: 'TCC803x/SW/Android/Android 14' }
              ],
            },
            {
              type: 'category',
              label: 'Android 15',
              items: [
                { type: 'autogenerated', dirName: 'TCC803x/SW/Android/Android 15' }
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Linux',
          items: [
            {
              type: 'category',
              label: 'YP4.0',
              items: [
                {
                  type: 'category',
                  label: 'V1.0.0',
                  items: [
                    { type: 'autogenerated', dirName: 'TCC803x/SW/Linux/YP4.0/V1.0.0' },
                  ],
                },
              ],
            },
          ],
        },
      ],
    },
  ],

  TCC805xSidebar: [
    {
      type: 'category',
      label: 'HW',
      items: [
        {
          type: 'category',
          label: 'Application Note',
          items: [
            { type: 'autogenerated', dirName: 'TCC805x/HW/Application Note' }
          ],
        },
        {
          type: 'category',
          label: 'User Guide',
          items: [
            { type: 'autogenerated', dirName: 'TCC805x/HW/User Guide' }
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'SW',
      items: [
        {
          type: 'category',
          label: 'Android',
          items: [
            {
              type: 'category',
              label: 'Android 13',
              items: [
                { type: 'autogenerated', dirName: 'TCC805x/SW/Android/Android 13' }
              ],
            },
            {
              type: 'category',
              label: 'Android 14',
              items: [
                { type: 'autogenerated', dirName: 'TCC805x/SW/Android/Android 14' }
              ],
            },
            {
              type: 'category',
              label: 'Android 15',
              items: [
                { type: 'autogenerated', dirName: 'TCC805x/SW/Android/Android 15' }
              ],
            },
          ],
        },
      ],
    },
  ],

  TCC807xSidebar: [
    {
      type: 'category',
      label: 'HW',
      items: [
        {
          type: 'category',
          label: 'Application Note',
          items: [
            { type: 'autogenerated', dirName: 'TCC807x/HW/Application Note' }
          ],
        },
        {
          type: 'category',
          label: 'User Guide',
          items: [
            { type: 'autogenerated', dirName: 'TCC807x/HW/User Guide' }
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'SW',
      items: [
        {
          type: 'category',
          label: 'Android',
          items: [
            {
              type: 'category',
              label: 'Android 13',
              items: [
                { type: 'autogenerated', dirName: 'TCC807x/SW/Android/Android 13' }
              ],
            },
            {
              type: 'category',
              label: 'Android 14',
              items: [
                { type: 'autogenerated', dirName: 'TCC807x/SW/Android/Android 14' }
              ],
            },
            {
              type: 'category',
              label: 'Android 15',
              items: [
                { type: 'autogenerated', dirName: 'TCC807x/SW/Android/Android 15' }
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Linux',
          items: [
            {
              type: 'category',
              label: 'YP4.0',
              items: [
                {
                  type: 'category',
                  label: 'V1.0.0',
                  items: [
                    { type: 'autogenerated', dirName: 'TCC807x/SW/Linux/YP4.0/V1.0.0' },
                  ],
                },
              ],
            },
          ],
        },
      ],       
    },
  ],
  TCCxxxxSidebar: [
    {
    type: 'category',
    label: 'HW',
    items: [
        { type: 'autogenerated', dirName: 'TCCxxxx/HW' },
      ],
    },
    {
    type: 'category',
    label: 'SW',
    items: [
        {
        type: 'category',
        label: 'Common',
        items: [
            { type: 'autogenerated', dirName: 'TCCxxxx/SW/Common' },
          ],
        },
      ],
    },
  ],

  TCC200xSidebar: [
    {
      type: 'category',
      label: 'HW',
      items: [
        {
          type: 'category',
          label: 'Application Note',
          items: [
            { type: 'autogenerated', dirName: 'TCC200x/HW/Application Note' }
          ],
        },
        {
          type: 'category',
          label: 'User Guide',
          items: [
            { type: 'autogenerated', dirName: 'TCC200x/HW/User Guide' }
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'SW',
      items: [
        {
          type: 'category',
          label: 'Android',
          items: [
            {
              type: 'category',
              label: 'Android 13',
              items: [
                { type: 'autogenerated', dirName: 'TCC200x/SW/Android/Android 13' }
              ],
            },
            {
              type: 'category',
              label: 'Android 14',
              items: [
                { type: 'autogenerated', dirName: 'TCC200x/SW/Android/Android 14' }
              ],
            },
            {
              type: 'category',
              label: 'Android 15',
              items: [
                { type: 'autogenerated', dirName: 'TCC200x/SW/Android/Android 15' }
              ],
            },
          ],
        },
      ],
    },
  ],
};
